# Generated by Django 5.1.6 on 2025-02-24 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyuncu',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
