# Generated by Django 5.1.6 on 2025-02-24 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='blue_team',
            field=models.ManyToManyField(blank=True, related_name='blue_lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobby',
            name='red_team',
            field=models.ManyToManyField(blank=True, related_name='red_lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
