# Generated by Django 5.1.6 on 2025-02-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_lobby_blue_team_lobby_red_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='current_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.kelime'),
        ),
    ]
