# Generated by Django 5.1.6 on 2025-02-24 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_lobby_current_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='ready_users',
            field=models.ManyToManyField(blank=True, related_name='ready_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
