# Generated by Django 5.1.6 on 2025-02-25 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_lobby_ready_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='ready_users',
        ),
        migrations.AddField(
            model_name='lobby',
            name='ready_players',
            field=models.ManyToManyField(blank=True, related_name='ready_in_lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oyuncu',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
