# Generated by Django 5.1.6 on 2025-02-25 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_lobby_ready_users_lobby_ready_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='storyteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby_as_storyteller', to=settings.AUTH_USER_MODEL),
        ),
    ]
