# Generated by Django 5.1.6 on 2025-02-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_lobby_storyteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='lobby_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lobby'),
        ),
    ]
