# Generated by Django 5.1.6 on 2025-02-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_friendrequest_lobby_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='blue_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='red_score',
            field=models.IntegerField(default=0),
        ),
    ]
