# Generated by Django 5.1.6 on 2025-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_lobby_blue_score_lobby_red_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='round_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
