# Generated by Django 5.1.6 on 2025-02-26 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_lobby_round_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='round_ready_players',
            field=models.ManyToManyField(blank=True, related_name='round_ready_in_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
