# Generated by Django 5.1.6 on 2025-02-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_lobby_round_ready_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
