# Generated by Django 5.1.6 on 2025-02-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_lobby_game_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_started',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
