# Generated by Django 5.1.6 on 2025-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_lobby_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='label_assignments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
