# Generated by Django 5.1.6 on 2025-02-27 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_lobby_label_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='current_explainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_explainer_lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobby',
            name='explainer_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
