# Generated by Django 5.1.6 on 2025-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_lobby_current_explainer_lobby_explainer_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='storyteller',
        ),
        migrations.AlterField(
            model_name='lobby',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
