# Generated by Django 5.1.6 on 2025-02-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_lobby_storyteller_alter_lobby_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='explainer_queue',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lobby',
            name='last_explainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_explainer_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
