# Generated by Django 5.1.6 on 2025-02-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_lobby_explainer_queue_lobby_last_explainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='last_explainer',
        ),
    ]
