# Generated by Django 5.1.6 on 2025-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_lobby_last_explainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabuWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_kelime', models.CharField(max_length=255)),
                ('yasakli_kelimeler', models.TextField()),
            ],
        ),
    ]
