# Generated by Django 5.1.6 on 2025-03-03 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_tabuword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaKelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TabuWord',
        ),
        migrations.AlterField(
            model_name='yasaklikelime',
            name='kelime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='yasaklikelime',
            name='ana_kelime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yasakli_kelimeler', to='game.anakelime'),
        ),
    ]
